### ISSUE TITLE
Meta/Open-Graph Tags (SSR Required)

### ISSUE THREAD

**Issue by robertkleinschuster** [TeamPiped/Piped#2459]
### Describe the feature

When sharing a Video-Link to Piped via Social-Media the preview should contain the Video-Title and Thumbnail.

### Why would this be useful to add?

Reduce confusion by the recipient.

### Concept(s)

Migrate to nodejs server with nuxt.js and use vue-meta package to dynamically assign meta data.

### Acknowledgements

- [x] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
We're already tracking that at #1362
